### ISSUE TITLE
Not reporting saved password

### ISSUE THREAD

**Issue by Sytehk** [Technowlogy-Pushpender/technowlogger#10]
The payload reports key logs and screenshots but not Saved passwords... do i need to declare an interval for it? or just assign the "-s" only when creating the payload?

**Comment by Technowlogy-Pushpender** [comment]
You only need to specify **-s** or **--steal-password** option.
This option does not takes any argument.

Also no particular time is fixed, password stealer works on different thread, but it will send the password logs under 1 min or 2 min [**Wherever the password retrieval process finished, then the logs are been send by keylogger**]

You will get the Saved password for once only, to get the password again, restart the PC and you will get the password again.

Or remove the keylogger completely and run it again.

**Comment by Technowlogy-Pushpender** [comment]
Improved the codes, please try again
