### ISSUE TITLE
Failed To Generate Your Payload Please Try Again!

### ISSUE THREAD

**Issue by sandman4812av** [Technowlogy-Pushpender/technowlogger#11]
when running technowlogger.py, OS Kali

python3 technowgen.py -e aaaaaaa@gmail.com -p aaaaaaaaaa -l -o /root/Desktop/testaa --icon /root/technowlogger/icon/docx.ico

---------------------------
[*] Deleting Junk Files...
rm: cannot remove '/root/Desktop/testaa.spec': No such file or directory
[+] Junk Files Removed Successfully!

[!] Failed To Generate Your Payload :(, Please Try Again!
---------------------------------------

+++ there're error also in windows install

![image](https://user-images.githubusercontent.com/29623610/71065389-2673c900-213f-11ea-9f07-e356a629adbc.png)

**Comment by Technowlogy-Pushpender** [comment]
For **windows**, try to run this command : `python -m pip install --upgrade pywin32`
And then try to re-run the installation i.e. run this command : `python -m pip install -r requirements.txt`

Also In **Kali Linux**:

Command should be like this:
`python3 technowgen.py -e aaaaaaa@gmail.com -p aaaaaaaaaa -w -o testaa --icon icon/docx.ico`

build-in binder feauture does not support  Linux payload , if you want to generate payload for windows then specify **-w**
, not matter whether you are in linux or windows  

File will be saved in `technowlogger/dist`

**Comment by sandman4812av** [comment]
same error after python -m pip install --upgrade pywin32

![image](https://user-images.githubusercontent.com/29623610/71091572-c4f33f00-21be-11ea-8be8-f9390e90a2ef.png)

my OS is Windows 10 64bit

**Comment by sandman4812av** [comment]
+++ same result in Kali with -w flag

![image](https://user-images.githubusercontent.com/29623610/71092299-f7784a00-2174-11ea-986e-a71885eb0d94.png)

**Comment by Technowlogy-Pushpender** [comment]
Wine must be installed on your kali system,
In Wine, you should install python of windows.

I think you forget to run **installer_linux.sh** , which will install python 32bit and required modules in your main machine as well as in wine .

If you have already run the script, then please check and update the path of pyinstaller in technowgen.py.

Script is working fine, the only problem you are facing is while compiling, script unable to find **pyinstaller**, which will be used to compile the source code.

**Comment by sandman4812av** [comment]
![image](https://user-images.githubusercontent.com/29623610/71144041-a4d97500-21ea-11ea-9c06-b19baccc0865.png)
![image](https://user-images.githubusercontent.com/29623610/71144051-ae62dd00-21ea-11ea-942a-794bf5f18306.png)
it gives some errors when running  installer_linux.sh.. please help to complete 

and what about windows
![image](https://user-images.githubusercontent.com/29623610/71144104-d81c0400-21ea-11ea-89ae-2822dfd6d53b.png)
