### ISSUE TITLE
error while generating, "rm" is not internal or external command, executable program or batch file.

### ISSUE THREAD

**Issue by sandman4812av** [Technowlogy-Pushpender/technowlogger#12]
I think solved these problems, but now another error while generating
-----------------------------

C:\Users\User\Desktop\cmder\tech>python technowgen.py -e test@gmail.com -p test -w -o D:/testaq --icon C:\Users\User\Desktop\cmder\tech\icon\docx.ico
**"rm" is not internal or external
command, executable program or batch file.**

I think it happens because rm command in .py file doesn't work in Windows OS but what can I do ?
thank you

 _______        _     _   _               _
|__   __|      | |   | \ | |             | |
   | | ___  ___| |__ |  \| | _____      _| |     ___   __ _  __ _  ___ _ __
   | |/ _ \/ __| '_ \| . ` |/ _ \ \ /\ / / |    / _ \ / _` |/ _` |/ _ \ '__|
   | |  __/ (__| | | | |\  | (_) \ V  V /| |___| (_) | (_| | (_| |  __/ |
   |_|\___|\___|_| |_|_| \_|\___/ \_/\_/ |______\___/ \__, |\__, |\___|_|
                                                       __/ | __/ |
                                                      |___/ |___/

                Author: Pushpender | Website: technowlogy.tk

[ * * * * * * * * * * * * * * * * * * * * * * * * * ]

   Email: test@gmail.com
   Password: test
   Log's Send Interval: Every 120 seconds
   Becomes Persistence After: 10 seconds
   Output Evil File Name: D:/testaq
   Icon Path: C:\Users\User\Desktop\cmder\tech\icon\docx.ico

[ * * * * * * * * * * * * * * * * * * * * * * * * * ]

[?] These info above are correct? (y/n) : y

[*] Checking Dependencies...
[+] All Dependencies are Installed on this system ;)

[*] Generating Please wait for a while...

[*] Encrypting Source Codes...
[+] Operation Completed Successfully!

**The system cannot find the path specified.**

[*] Deleting Junk Files...
[+] Junk Files Removed Successfully!

[!] Failed To Generate Your Payload :(, Please Try Again!

[:D] Please Contact us on https://github.com/Technowlogy-Pushpender/technowlogger

C:\Users\User\Desktop\cmder\tech>

**Comment by Technowlogy-Pushpender** [comment]
YOU : **The system cannot find the path specified.**

There is no issue in the script, Please Don't put these types of issues,

Clearly mentioned in the README.md that `PLEASE UPDATE THE pyinstaller path in technowgen.py`

As you might installed python on different place and its path will differ from the default path

Also **-o** or **--output** Argument only takes File name, not the path

Also If you are getting errors while installing in kali linux using **installer_linux.sh**
then simply open installer_linux.sh in text editor and then execute the each command manually

installer_linux.sh in just updated with few improvements, please check

**Comment by Technowlogy-Pushpender** [comment]
**"rm" is not internal or external
command, executable program or batch file.**

This Issue is Fixed

**Comment by sandman4812av** [comment]
![image](https://user-images.githubusercontent.com/29623610/71172829-4387c500-222f-11ea-8fd0-bb22484898d1.png)

downloaded latest version, there is rm error again stills and it doesn't send logs after first sending :(

**Comment by sandman4812av** [comment]
I removed --noconsole from line 167, 169, 173, 175  but it doesn't send logs after first sending
![image](https://user-images.githubusercontent.com/29623610/71175511-bd22b180-2235-11ea-8df7-1fef953df223.png)
and it runs in background but doesn't send logs
![image](https://user-images.githubusercontent.com/29623610/71175516-c1e76580-2235-11ea-80ad-6a3beb2e07dc.png)

**Comment by sandman4812av** [comment]
any updates ?
