### ISSUE TITLE
help me fix error:

### ISSUE THREAD

**Issue by phanthuthao** [Technowlogy-Pushpender/technowlogger#14]

**Comment by phanthuthao** [comment]
root@markenal:/opt/technowlogger# python technowgen.py --help
  File "technowgen.py", line 19
    parser = argparse.ArgumentParser(description=f'{RED}TechNowLogger v1.6')
                                                                          ^
SyntaxError: invalid syntax
help me fix this error! Thanks so much

**Comment by Technowlogy-Pushpender** [comment]
Please Run it using python3
like this `python3 technowgen.py --help`

Also, clone the fresh version, minor issue is fixed

**Comment by Enkiggu** [comment]
hey i am using python3 but it says Traceback (most recent call last):
  File "technowgen.py", line 8, in <module>
    from essential_generators import DocumentGenerator
ModuleNotFoundError: No module named 'essential_generators'
help me for fix it pls
