### ISSUE TITLE
bash: event not found.

### ISSUE THREAD

**Issue by jepunband** [Technowlogy-Pushpender/technowlogger#16]
$sudo python3 technowgen.py -w -o sleep -e mytestemail@gmail.com -p !@0Xty5R#$
bash: !@0Xty5R#$: event not found
-------
technowlogger does not accept complex gmail passwords that has special characters ..

**Comment by Technowlogy-Pushpender** [comment]
Its Working fine, maybe you are using that password which contains some character which are meaningful to bash interpreter
