### ISSUE TITLE
E: Package 'pyinstaller' has no installation candidate

### ISSUE THREAD

**Issue by jepunband** [Technowlogy-Pushpender/technowlogger#17]
Package pyinstaller is a virtual package provided by:
  python3-pyinstaller 3.5-0kali2
  python-pyinstaller 3.5-0kali1
You should explicitly select one to install.

E: Package 'pyinstaller' has no installation candidate
E: Unable to locate package 
--2020-01-31 19:58:23--  https://www.python.org/ftp/python/3.7.4/python-3.7.4.exe
Resolving www.python.org (www.python.org)... 151.101.8.223, 2a04:4e42:2::223
Connecting to www.python.org (www.python.org)|151.101.8.223|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 25663848 (24M) [application/octet-stream]

i tried install using both, same error ... "python3-pyinstaller, and" python-pyinstaller" .
$pyinstaller --version
3.6

**Comment by Technowlogy-Pushpender** [comment]
This is not a issue with the script, it is a issue related to your kali machine. Please Try to Update your source.list and then update your aptitude manager 
`Source List Path: /etc/apt/sources.list`

Update Your Aptitude Manager: `apt-get update`
