### ISSUE TITLE
Couldn't figure out how it runs in linux 

### ISSUE THREAD

**Issue by yathomasi** [Technowlogy-Pushpender/technowlogger#2]
does it run in wine in linux 
how to find out its running in background
The script run completed but got no message
can you review it please

**Comment by Technowlogy-Pushpender** [comment]
It is coded it that manner that it does not show any message when victim
runs it.
Evil file generated using technowlogger has the ability to become self
persistence by detecting OS and executing the persistence method
accordingly.

And yes it run's in wine in Linux,
as if you want to make keylogger for windows os from linux, then you have
to use wine as well as python of windows
Please run "installer_linux.sh" to configure it automatically

if you want to find the process id then it is too simple bro,
type "ps" in terminal and find process with the name of keylogger which you
named while creating keylogger.

How to remove Keylogger in Linux:
--------------------------------------------------

Open Autostart file with any text editor,
Autostart File Path: ~/.config/autostart/xinput.desktop

Remove these 5 lines:
[Desktop Entry]
Type=Application
X-GNOME-Autostart-enabled=true
Name=Xinput
Exec="destination_file_name"


Destination Path, where Keylogger is stored : ~/.config/xnput

Hope, this is helpful to you.

Please visit : Website <https://www.technowlogy.tk>
to know more about ethical hacking and free stuff

**Comment by Technowlogy-Pushpender** [comment]
Hope your issue is sort out, if you face any other issue then let me know
