### ISSUE TITLE
Killing Antivirus services on this pc

### ISSUE THREAD

**Issue by Hannes0084** [Technowlogy-Pushpender/technowlogger#24]
Hi, i get the following when executing the payload. I create a windows payload and the build has got no errors. but when i add --debug i get the following :

System error 5 has occurred.

Access is denied.

[*] Killing Antivirus services on this pc

i used the previous version without any issues.

kind regards

**Comment by Technowlogy-Pushpender** [comment]
The error you encounter, is of windows security disabler

Technowlogger fails to disable the windows security because of less
privileges

Just run the exe with admin privileges

And you are good to go

And also, it will not affect the keylogger functionality so there is no
need to worry

**Comment by Hannes0084** [comment]
Hi, first of all thanks for the feedback. Awesome program.

I am running the exe with admin privileges.
i just tested again and still the issue persists.

Anything else i can try?

i'm running Windows 10 version  10.0.18363 N/A Build 18363

thanks
