### ISSUE TITLE
Why generator error ???

### ISSUE THREAD

**Issue by ImOnlyUser** [Technowlogy-Pushpender/technowlogger#4]
![fesadgs](https://user-images.githubusercontent.com/34210076/69902476-b0c1dc00-138e-11ea-8b0f-52493f9b0931.png)

Why is this happening?

**Comment by Y0pek** [comment]
btw: this is Linux Console

**Comment by ImOnlyUser** [comment]
> ![fesadgs](https://user-images.githubusercontent.com/34210076/69902476-b0c1dc00-138e-11ea-8b0f-52493f9b0931.png)
> 
> Why is this happening?

**Comment by Technowlogy-Pushpender** [comment]
You might not defined   -w or -l arguments

these are arguments are required to tell the script that which OS you are
using and for which system you want to create payload.

if you are on linux,  specify -l
