### ISSUE TITLE
Error while generating

### ISSUE THREAD

**Issue by ImOnlyUser** [Technowlogy-Pushpender/technowlogger#5]
### **When generating "the system cannot find the path specified" why?**

**Comment by ImOnlyUser** [comment]
![pr00blem](https://user-images.githubusercontent.com/34210076/69978687-2e235300-152d-11ea-8b6e-c8eafa8ad0c9.png)
**I detected an error. What could I do next? Maybe someone will suggest?**

**Comment by Technowlogy-Pushpender** [comment]
So the Error is encountered while compiling.

If you are on windows, please update the **WINDOWS_PYTHON_PYINSTALLER_PATH** variable,

By default, it is set to **WINDOWS_PYTHON_PYINSTALLER_PATH = "C:/Python37-32/Scripts/pyinstaller.exe"**

Also If you are in Linux, then try to execute this command : **pyinstaller** 
If you failed to run this command. that means, **pyinstaller** is not installer in your system

Simply run this command to install it, **python3 -m pip install pyinstaller**

Remove these last two lines, it will going to show error in more details, post that error to us

    **except Exception as e:**
         **print(f"\n{RED}[!] Error : {e}")**

**Comment by Technowlogy-Pushpender** [comment]
Also tell us which command you are using and which OS you are using

**Comment by Technowlogy-Pushpender** [comment]
Just Updated Technowlogger. 

Download fresh file and then
Please try to re-run **installer_linux.sh** and then run technowgen.py
