### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by diewithurlie** [Technowlogy-Pushpender/technowlogger#8]
Command "python setup.py egg_info" failed with error code 1 in C:\Users\XXX\AppData\Local\Temp\pip-build-uwp4gwn7\win32gui\

**Comment by Technowlogy-Pushpender** [comment]
Which python version you are using, recommended to use python 3.7.4 32bit

Also run this command : `python -m pip install pywin32`

This is link of Offline pywin32 module, in case you are unable to install **pywin32** 
https://www.lfd.uci.edu/~gohlke/pythonlibs/#pywin32
